### ISSUE TITLE
Adding VERY useful and really necessary functions

### ISSUE THREAD

**Issue by katchinnn** [thomasmny/BuildSystem#164]
### What problem does this feature solve?

Add separate permissions to edit worlds, because if you give the permission "buildsystem.edit" or "buildsystem.edit. <option> (placement for example)" to a player, the player will be able to use this edit option in his private world and in all the other worlds even if they are private, that the menu, or its interface and design itself is configurable, because really for many, and I am more than sure I am not the only one, the design that comes in the menu may not be to your taste or want to add / remove certain things like panels, adjust the slots of the items in the menus etc.. .., so I think this would be very useful and great to have for a future version. (:

**Comment by thomasmny** [comment]
> Add separate permissions to edit worlds, because if you give the permission "buildsystem.edit" or "buildsystem.edit. (placement for example)" to a player, the player will be able to use this edit option in his private world and in all the other worlds even if they are private

If I understand you correctly, this is already implemented: https://buildsystem.eintosti.com/permissions/commands#restricting-worlds
Make sure your player doesn't have the admin permission (`buildsystem.admin`) otherwise that bypasses the restriction.

> the menu, or its interface and design itself is configurable

I can assure you that this won't be added any time soon as the current implementation of the menus would make it quite exhausting to implement.
However, feel free to fork the project and redesign the inventories to your liking.

**Comment by katchinnn** [comment]
oh, 

> > Agregue permisos separados para editar mundos, porque si otorga el permiso "buildsystem.edit" o "buildsystem.edit. (ubicación, por ejemplo)" a un jugador, el jugador podrá usar esta opción de edición en su mundo privado y en todos los otros mundos aunque sean privados
> 
> Si te entiendo correctamente, esto ya está implementado: https://buildsystem.eintosti.com/permissions/commands#restricting-worlds Asegúrate de que tu jugador no tenga el permiso de administrador ( `buildsystem.admin`), de lo contrario, se salta la restricción.
> 
> > el menú, o su interfaz y el diseño en sí es configurable
> 
> Les puedo asegurar que esto no se agregará en el corto plazo, ya que la implementación actual de los menús haría que la implementación fuera bastante agotadora. Sin embargo, siéntete libre de bifurcar el proyecto y rediseñar los inventarios a tu gusto.

oh, great, thanks you! (:

**Comment by thomasmny** [comment]
Will close, as I still stand by my reply
