### ISSUE TITLE
Eigener Maps Ordner

### ISSUE THREAD

**Issue by SorrowFinest** [thomasmny/BuildSystem#166]
### What problem does this feature solve?

Ein ordner in dem alle Maps die durch das Buildsystem erstellt wurden gespeichert sind.
Wäre übersichtlicher und hoffe das das Funktioniert.

**Comment by thomasmny** [comment]
Already exists in `bukkit.yml` (https://bukkit.fandom.com/wiki/Bukkit.yml#world-container)
