### ISSUE TITLE
Add an option that allows us to modify the regular expression for restricting world names.

### ISSUE THREAD

**Issue by TWME-TW** [thomasmny/BuildSystem#190]
### What problem does this feature solve?

Add an option that allows us to modify the regular expression for restricting world names.

This allows us to restrict some characters,like `/`

**Comment by thomasmny** [comment]
Do you think the characters should be removed or should the creation be cancelled?

**Comment by TWME-TW** [comment]
Can you show me where this code (regular expression) is?  (I want to make changes in my own version first

**Comment by thomasmny** [comment]
This is definitely **one** place:
https://github.com/thomasmny/BuildSystem/blob/eb2060628ee21cd1203f8355861dc05b6dedcade/buildsystem-core/src/main/java/com/eintosti/buildsystem/world/WorldManager.java#L178

Might be more, just on my phone atm
