### ISSUE TITLE
Worlds: world import failure

### ISSUE THREAD

**Issue by itsme-to** [thomasmny/BuildSystem#245]
### Steps to reproduce

- Configure `level-name` to `maps/world`
- All world will now be in the /maps folder. It's for more easly manage them.
- Try /worlds import world or /worlds importAll

### What is expected?

Load the world with success

### What is actually happening?

Error when the command is executed:
[2024-01-18-16.log](https://github.com/thomasmny/BuildSystem/files/13982604/2024-01-18-16.log)

Error when the server restart:
[2024-01-18-17.log](https://github.com/thomasmny/BuildSystem/files/13982607/2024-01-18-17.log)

### Server Info

```shell
1.20.1 Paper
```

**Comment by thomasmny** [comment]
I assume you want to store your worlds in a separate folder?
The correct way to do so is by setting `world-container` in your `bulkit.yml` file:
```yaml
settings:
  world-container: map
```
Then you name the world normally (e.g. TestWorld) and it will be stored in `/maps/TestWorld/`

**Comment by thomasmny** [comment]
I'll close this as I have not received a response in a while.

If you have tried my suggested method and the error still persists, please re-open this issue or create a new one
