### ISSUE TITLE
Axiom Support

### ISSUE THREAD

**Issue by EinJOJO** [thomasmny/BuildSystem#304]
### What problem does this feature solve?

Restrict Axiom usage like its done with WorldEdit.

AxiomPaper Events:
https://github.com/Moulberry/AxiomPaperPlugin/tree/cdcece8f883b9a55fdf0ec8707730c1d2ac00795/src/main/java/com/moulberry/axiom/event

**Comment by EinJOJO** [comment]
starting implementing axiom-support on my fork.

**Comment by Lumine1909** [comment]
> starting implementing axiom-support on my fork.

Great, thank you for that.
Without that, I have to add an extra permission to AxiomPaper for handle permission.

If you need help for that feature, feel free to contact me : )

**Comment by EinJOJO** [comment]
See #309
